name: docker-build-publish

on:
  workflow_dispatch:

jobs:
    build-docker-image:
      runs-on: ubuntu-latest

      permissions:
        contents: read
        packages: write

      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: login to ghcr
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: build and publish image
          run: |
            docker build -t translateit .
            docker push translateit

